tap "ciiiii/tap", "https://github.com/ciiiii/homebrew-tap.git"
tap "microsoft/git"
tap "openresty/brew"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

brew "go"
brew "rustup-init"

brew "lsd"
brew "neovim"
brew "ripgrep"
brew "gnupg"
brew "svn"
brew "yadm"
brew "pyenv"
brew "dvm"
brew "colima"
brew "kubectl"
brew "helm"
brew "terraform"
brew "awscli"
brew "aws-vault"

brew "ciiiii/tap/kube-proxycommand"
brew "openresty/brew/openresty"

cask "iterm2"
cask "raycast"
cask "snipaste"
cask "visual-studio-code"
cask "typora"
cask "google-cloud-sdk"

cask "microsoft/git/git-credential-manager-core"
cask "homebrew/cask-versions/firefox-developer-edition"

cask "homebrew/cask-fonts/font-fira-code"
cask "homebrew/cask-fonts/font-source-code-pro"
cask "homebrew/cask-fonts/font-hack-nerd-font"
cask "homebrew/cask-fonts/font-droid-sans-mono-for-powerline"