tap "ciiiii/tap", "https://github.com/ciiiii/homebrew-tap.git"
tap "microsoft/git"

brew "lsd"
brew "neovim"
brew "ripgrep"
brew "gnupg"

brew "go"
brew "rustup-init"

brew "openresty"
brew "yadm"
brew "pyenv"
brew "dvm"
brew "colima"
brew "kubectl"
brew "helm"
brew "terraform"
brew "awscli"
brew "aws-vault"

brew "ciiiii/tap/kube-proxycommand"

cask "iterm2"
cask "raycast"
cask "snipaste"
cask "visual-studio-code"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "typora"
cask "google-cloud-sdk"
cask "git-credential-manager-core"
