#!/usr/bin/expect
if { $argc < 1 } {
    spawn ssh jumpserver
    interact
    exit
}

set HOST [lindex $argv 0]

catch { spawn ssh jumpserver }
expect {
    "Opt>"
    {
        send "$HOST\r"
    }
}
expect {
    "*error*"
    {
        exit 1
    }
}
expect {
    "$env(JUMPSERVER_HOSTNAME)*"
    {
        send "sudo su\r"
    }
    
}
expect {
    "*\[sudo\]*"
    { send "$env(JUMPSERVER_PASSWORD)\r" }
}
interact